### ISSUE TITLE
Version 1.20 breaks custom annotation suppression

### ISSUE THREAD

**Issue by TimvdLippe** [mojohaus/animal-sniffer#172]
At Mockito, we have https://github.com/mockito/mockito/pull/2208 lying around for a while. Unfortunately it was failing our CI and I never had the time to look into. Today, I decided to take a look and it fails compilation with the following message:

```
> Task :animalsnifferMain FAILED

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineBytecodeGenerator.java::1)
  >> java.lang.instrument.Instrumentation

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineDelegateByteBuddyMockMaker.java::1)
  >> java.lang.instrument.Instrumentation

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.util.reflection.(InstrumentationMemberAccessor.java::1)
  >> java.lang.instrument.Instrumentation

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.util.reflection.(InstrumentationMemberAccessor.java::1)
  >> java.lang.invoke.MethodHandles.Lookup
```

This is somewhat surprising, as all of these classes (intentionally) use Java 8+ APIs that don't run on Android. As such, we suppress these classes (example: https://github.com/mockito/mockito/blob/96883a1fa39f29146144f9ccf2e43e9932dca6a1/src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java#L49)

The PR in question updates https://github.com/xvik/gradle-animalsniffer-plugin which according to https://github.com/xvik/gradle-animalsniffer-plugin/releases/tag/1.5.3 updates AnimalSniffer from 1.18 to 1.20. As such, I suspect that somewhere in that timeframe, the reporting broke.

Interestingly, when I removed the suppression annotation from `InlineBytecodeGenerator`, it produced the following output:

```
> Task :animalsnifferMain FAILED

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineBytecodeGenerator.java::1)
  >> java.lang.instrument.Instrumentation

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineBytecodeGenerator.java:168)
  >> void java.lang.instrument.Instrumentation.addTransformer(java.lang.instrument.ClassFileTransformer, boolean)

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineBytecodeGenerator.java:276)
  >> void java.lang.instrument.Instrumentation.retransformClasses(Class[])

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineBytecodeGenerator.java:412)
  >> void java.lang.instrument.Instrumentation.retransformClasses(Class[])

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineBytecodeGenerator.java:413)
  >> java.lang.instrument.UnmodifiableClassException

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.creation.bytebuddy.(InlineDelegateByteBuddyMockMaker.java::1)
  >> java.lang.instrument.Instrumentation

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.util.reflection.(InstrumentationMemberAccessor.java::1)
  >> java.lang.instrument.Instrumentation

[Undefined reference | android-api-level-24-7.0_r2] org.mockito.internal.util.reflection.(InstrumentationMemberAccessor.java::1)
  >> java.lang.invoke.MethodHandles.Lookup
```

As you can see, it now includes the real issues on the correct lines, but it *also* includes the `:1` error. Could it be that the `:1` error is related to the import of the type (which it should ignore?): https://github.com/mockito/mockito/blob/96883a1fa39f29146144f9ccf2e43e9932dca6a1/src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java#L36

In any case, it seems like 1.20 or 1.19 regressed suppression of the violations when you attach the annotation to the class. I also tried to move the suppression annotation to all unique lines, but the `:1` error keeps on being reported.

**Comment by cpovirk** [comment]
(This sounds like https://github.com/mojohaus/animal-sniffer/issues/131.)

**Comment by olamy** [comment]
fixed

**Comment by Marcono1234** [comment]
> (This sounds like #131.)

Yes I think there multiple things which come together here:
1. The description above says:
    > updates AnimalSniffer from 1.18 to 1.20. As such, I suspect that somewhere in that timeframe, the reporting broke.

    A check for the field type was added in version 1.19: #75
2. The check for the field type ignores annotations on the enclosing class: #131
3. animal-sniffer provides no line number for fields (see also  #132) and gradle-animalsniffer-plugin in that cases shows 1 as line number ([relevant source code](https://github.com/xvik/gradle-animalsniffer-plugin/blob/cb43c4a5eb4b87d665001fd80851a79150750e46/src/main/groovy/ru/vyarus/gradle/plugin/animalsniffer/util/FormatUtils.groovy#L86))

**Comment by cstamas** [comment]
This issue is not fixed (or is broken again). In face, on Java 8 it works only up to 1.16, and later version all way to latest do not.

**Comment by Marcono1234** [comment]
@cstamas, do you have a small example project demonstrating this? And does this affect fields or also other members?
Because it seems the issue originally reported here was about fields and annotations on enclosing classes, and that was apparently fixed.

**Comment by cstamas** [comment]
https://github.com/netty/netty/blob/52cd25e01d1169e721b7f3ca7af3d849087b3bfe/pom.xml#L1577-L1604

I was making Netty build "Maven4 friendly", and I could not go past 1.16 release, as all the other failed due annotation not being detected. Will create an issue when I will know more.
